# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclLsp < Formula
  desc "KCL Language Server"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.14.3"
  license "Apache License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.3/kclipper_Darwin_x86_64", using: CurlDownloadStrategy
      sha256 "eeaa5b72b5414cea092677d174f307ebe8a7b37bb32d9fe01590bcfa31146ae5"

      def install
        bin.install "kcl-language-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.3/kclipper_Darwin_arm64", using: CurlDownloadStrategy
      sha256 "81914da220b0ee82d9b61516fafcf1377edc986c161e4cd8de03c59e803882d9"

      def install
        bin.install "kcl-language-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.3/kclipper_Linux_x86_64", using: CurlDownloadStrategy
      sha256 "3c963c04ebd2ecc10a382f9c8f77230ddb3c1b54fd58c1e09eee33a1f3680332"
      def install
        bin.install "kcl-language-server"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.3/kclipper_Linux_arm64", using: CurlDownloadStrategy
      sha256 "9683a118dc0671b64afe5e6cfb8fa61e45b52fbad51b62a377ea668367f5836c"
      def install
        bin.install "kcl-language-server"
      end
    end
  end

  test do
    system "#{bin}/kcl-language-server version"
  end
end
