# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KclLsp < Formula
  desc "KCL Language Server"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.14.4"
  license "Apache License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.4/kclipper_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "2f1b2fe741b7b9e12321c7f34b75da6e2633a76477d35778181f0840fe3ca7d6"

      def install
        bin.install "kcl-language-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.4/kclipper_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "46e61ab1b302c168442da0820f9c95d699c4daa5bfeba420dc28fd0c4e29c261"

      def install
        bin.install "kcl-language-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.4/kclipper_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b163ec21c69b8532dc83fd341fe5e38d62148a493f03a079601994fdd37e97d5"
      def install
        bin.install "kcl-language-server"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.4/kclipper_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7db37a067c30cdc280757499b67b593c10e53be01944a0226240cb7a7eab16f9"
      def install
        bin.install "kcl-language-server"
      end
    end
  end

  test do
    system "#{bin}/kcl-language-server version"
  end
end
