# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kclipper < Formula
  desc "Kclipper Command Line Interface"
  homepage "https://github.com/MacroPower/kclipper"
  version "0.14.2"
  license "Apache License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.2/kclipper_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "a1e7e46dd2fe448c1953028688c761ced90c3b058681ca6470fcfc5fb40753ae"

      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.2/kclipper_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f205ef83fbec38308a2a3bb085019b0b7b42c289d9bba3b818aeccdbb1dddbe8"

      def install
        bin.install "kcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.2/kclipper_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1ef9618acf9676339a7993d421090124e243ee68319ab52d1ea855c25b545a25"
      def install
        bin.install "kcl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/MacroPower/kclipper/releases/download/v0.14.2/kclipper_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ec298529e7c196982f9ac65d12dad83392f15809f13cb0978cd33aed0285a014"
      def install
        bin.install "kcl"
      end
    end
  end

  test do
    system "#{bin}/kcl version"
  end
end
