# This file was generated by GoReleaser. DO NOT EDIT.
cask "hcp_archiver" do
  version "0.11.1"

  on_macos do
    on_intel do
      sha256 "9eec4aa83bb53ba34dfaf3c7af02f10767f702a9d64fd236ec7c9db04f65bef6"
      url "https://git.jacobcolvin.com/hcp_archiver/releases/download/v#{version}/hcp_archiver_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "be2000c8e1cfc3910ed0b3fbe80f7d0ce2c9664567e8f27263bdb4c4b4508be1"
      url "https://git.jacobcolvin.com/hcp_archiver/releases/download/v#{version}/hcp_archiver_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5929c21ebcb8e3946907cfc839e6e094619e119823e1334fbd089b358fffe961"
      url "https://git.jacobcolvin.com/hcp_archiver/releases/download/v#{version}/hcp_archiver_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "57e0c8f21434a986521b8eae4257197962b96b40319c7b3f3ef6b4600db96fcb"
      url "https://git.jacobcolvin.com/hcp_archiver/releases/download/v#{version}/hcp_archiver_Linux_arm64.tar.gz"
    end
  end

  name "hcp_archiver"
  desc "Archives an HCP Terraform organization to plain files on disk"
  homepage "https://git.jacobcolvin.com/hcp_archiver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hcp_archiver"
  manpage "man/hcp_archiver.1"
  bash_completion "completion/bash/hcp_archiver.bash"
  fish_completion "completion/fish/hcp_archiver.fish"
  zsh_completion "completion/zsh/_hcp_archiver"

  # No zap stanza required

end
