# This file was generated by GoReleaser. DO NOT EDIT.
cask "hcp_archiver" do
  version "0.10.3"

  on_macos do
    on_intel do
      sha256 "08380cf7c44917a87b887e374186fe4ce33da7e471edc05b7896ad8c8734afba"
      url "https://github.com/MacroPower/hcp_archiver/releases/download/v#{version}/hcp_archiver_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6ec3cc8e06112a5f83164ab8bbcbca42e835ae67af2a466d9070392d53289e25"
      url "https://github.com/MacroPower/hcp_archiver/releases/download/v#{version}/hcp_archiver_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7b26f0fd261ad8b6ee72e708aaae048a090d8ab8dd5824d682ff794ca4e9417b"
      url "https://github.com/MacroPower/hcp_archiver/releases/download/v#{version}/hcp_archiver_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "46f7207c324e1cfeec2aaa8ff01a19bc21736c136af931f37c8fc9b167ca90aa"
      url "https://github.com/MacroPower/hcp_archiver/releases/download/v#{version}/hcp_archiver_Linux_arm64.tar.gz"
    end
  end

  name "hcp_archiver"
  desc "Archives an HCP Terraform organization to plain files on disk"
  homepage "https://github.com/MacroPower/hcp_archiver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hcp_archiver"
  manpage "man/hcp_archiver.1"
  bash_completion "completion/bash/hcp_archiver.bash"
  fish_completion "completion/fish/hcp_archiver.fish"
  zsh_completion "completion/zsh/_hcp_archiver"

  # No zap stanza required

end
