# This file was generated by GoReleaser. DO NOT EDIT.
cask "hcp_archiver" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "24fe418b16fae9e42e03e67f1fcc1dae467f33bee41a05fc7e7940be0ba09911"
      url "https://git.jacobcolvin.com/hcp_archiver/releases/download/v#{version}/hcp_archiver_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "62a5646590934de2662ed2b96308abcd284d33a15bc7a8716144c5452a5ce970"
      url "https://git.jacobcolvin.com/hcp_archiver/releases/download/v#{version}/hcp_archiver_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "45e9fc184d24357f9ede7924cd94918d7b8dab02b926f2a5452e5d5a06cd05dd"
      url "https://git.jacobcolvin.com/hcp_archiver/releases/download/v#{version}/hcp_archiver_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "15e22bea7599557e825cb8f794787b7249bbcb3987c5e4a22b13ae377df105f7"
      url "https://git.jacobcolvin.com/hcp_archiver/releases/download/v#{version}/hcp_archiver_Linux_arm64.tar.gz"
    end
  end

  name "hcp_archiver"
  desc "Archives an HCP Terraform organization to plain files on disk"
  homepage "https://git.jacobcolvin.com/hcp_archiver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hcp_archiver"
  manpage "man/hcp_archiver.1"
  bash_completion "completion/bash/hcp_archiver.bash"
  fish_completion "completion/fish/hcp_archiver.fish"
  zsh_completion "completion/zsh/_hcp_archiver"

  # No zap stanza required

end
