# This file was generated by GoReleaser. DO NOT EDIT.
cask "kat" do
  desc "TUI for rendering, validating, and displaying local Kubernetes manifests"
  homepage "https://github.com/MacroPower/kat/"
  version "0.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kat"

  on_macos do
    on_intel do
      url "https://github.com/MacroPower/kat/releases/download/v0.13.0/kat_Darwin_x86_64.tar.gz"
      sha256 "958c6d7ce4e39b8ef8b74e8891038caeefb48197d52412cc6afc0cbd758169c8"
    end
    on_arm do
      url "https://github.com/MacroPower/kat/releases/download/v0.13.0/kat_Darwin_arm64.tar.gz"
      sha256 "59d2b7eba83f875d291cd862a3f222ede825ccceae0e3f411c78164a1849f25b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MacroPower/kat/releases/download/v0.13.0/kat_Linux_x86_64.tar.gz"
      sha256 "44cda3f6f15ab9842498eb017f927bc448475cf291dc7ca9a29816c388ad4777"
    end
    on_arm do
      url "https://github.com/MacroPower/kat/releases/download/v0.13.0/kat_Linux_arm64.tar.gz"
      sha256 "d9c5ad030fea8d6fded26a9fa971987d3d12707e3014fd6010b838135c8dce1e"
    end
  end

  conflicts_with formula: [
      "kat",
    ]

  # No zap stanza required
end
