# This file was generated by GoReleaser. DO NOT EDIT.
cask "kat" do
  name "kat"
  desc "TUI for rendering, validating, and displaying local Kubernetes manifests"
  homepage "https://github.com/MacroPower/kat/"
  version "0.28.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kat"
  manpage "man/kat.1"
  bash_completion "completion/bash/kat.bash"
  zsh_completion "completion/zsh/_kat"
  fish_completion "completion/fish/kat.fish"

  on_macos do
    on_intel do
      url "https://github.com/MacroPower/kat/releases/download/v#{version}/kat_Darwin_x86_64.tar.gz"
      sha256 "4c3837acac2cbca6970f8b27cdbfabcb1110e16ccc7b68c8b9879329593ca401"
    end
    on_arm do
      url "https://github.com/MacroPower/kat/releases/download/v#{version}/kat_Darwin_arm64.tar.gz"
      sha256 "8da7fea99fd61294910c9111315da71a34afb327615bc818d148522df4e3af76"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MacroPower/kat/releases/download/v#{version}/kat_Linux_x86_64.tar.gz"
      sha256 "b066ed43ad95deadc32de3002316ecce2949c86f50c4c29f29c350327ebd28b4"
    end
    on_arm do
      url "https://github.com/MacroPower/kat/releases/download/v#{version}/kat_Linux_arm64.tar.gz"
      sha256 "87c26a1af23fd0d38dcd8cd79cfb540352384ce979e8932e728e3e998a6c75a3"
    end
  end

  # No zap stanza required
end
