# This file was generated by GoReleaser. DO NOT EDIT.
cask "kcl-lsp" do
  desc "KCL Language Server"
  homepage "https://github.com/kcl-lang/kcl"
  version "0.16.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kcl-language-server"

  on_macos do
    on_intel do
      url "https://github.com/macropower/kclipper/releases/download/v0.16.2/kclipper_Darwin_x86_64.tar.gz"
      sha256 "2af2da984a2c1cb599e5fde51a83338a9e5712d509c0904f276459e9e50ba330"
    end
    on_arm do
      url "https://github.com/macropower/kclipper/releases/download/v0.16.2/kclipper_Darwin_arm64.tar.gz"
      sha256 "f724a7443862344cde38c707d7054318ea8abbe9b6e6e3047f2b51392a12c090"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/macropower/kclipper/releases/download/v0.16.2/kclipper_Linux_x86_64.tar.gz"
      sha256 "30163ffd43a9da8bf439f4514f543cbf8634fe263598c08d5814ad247e4de808"
    end
    on_arm do
      url "https://github.com/macropower/kclipper/releases/download/v0.16.2/kclipper_Linux_arm64.tar.gz"
      sha256 "1d1d0173104ab6f9d859c0c70ecbeb6760441a44c4e9900cccabf5c0f0525e93"
    end
  end

  # No zap stanza required
end
