# This file was generated by GoReleaser. DO NOT EDIT.
cask "kclipper" do
  desc "Kclipper Command Line Interface"
  homepage "https://github.com/macropower/kclipper"
  version "0.15.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kclipper"
  depends_on cask: [
      "macropower/tap/kcl-lsp",
    ]

  on_macos do
    on_intel do
      url "https://github.com/macropower/kclipper/releases/download/v0.15.0/kclipper_Darwin_x86_64.tar.gz"
      sha256 "ad84196cb416be90bd7cca0f2162c9fdeb25999a34969a072add6e6530881f86"
    end
    on_arm do
      url "https://github.com/macropower/kclipper/releases/download/v0.15.0/kclipper_Darwin_arm64.tar.gz"
      sha256 "1e1881252ced730481f7b109a7d8f55087401f870402c3c3a573f4de371a158d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/macropower/kclipper/releases/download/v0.15.0/kclipper_Linux_x86_64.tar.gz"
      sha256 "411804057a720ed4b2cefbbe1e41370af639c9386a404ee4b8a698bae069bdb4"
    end
    on_arm do
      url "https://github.com/macropower/kclipper/releases/download/v0.15.0/kclipper_Linux_arm64.tar.gz"
      sha256 "329c8ad48111de9720004cfd25124c0081517c666bea35e845630ead3fa8d768"
    end
  end

  # No zap stanza required
end
