# This file was generated by GoReleaser. DO NOT EDIT.
cask "kclipper" do
  name "kclipper"
  desc "Kclipper Command Line Interface"
  homepage "https://github.com/macropower/kclipper"
  version "0.17.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kcl"

  on_macos do
    on_intel do
      url "https://github.com/macropower/kclipper/releases/download/v#{version}/kclipper_Darwin_x86_64.tar.gz"
      sha256 "c5c7bc630cebf870e224e043c111ca91169f424c05057c326c29255b9ba8df32"
    end
    on_arm do
      url "https://github.com/macropower/kclipper/releases/download/v#{version}/kclipper_Darwin_arm64.tar.gz"
      sha256 "e227cdce9a1d9de8010255201cfa0b6cad5b4f412d62fc404091a47457f8e786"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/macropower/kclipper/releases/download/v#{version}/kclipper_Linux_x86_64.tar.gz"
      sha256 "c51b8b4f6caec0c01128fb3d4199ffe7d3d254d22384924952c7851a0ecd8a79"
    end
    on_arm do
      url "https://github.com/macropower/kclipper/releases/download/v#{version}/kclipper_Linux_arm64.tar.gz"
      sha256 "04334b1877c2625e001853f0f295c11710cc444a01622306800cec3015c611df"
    end
  end

  # No zap stanza required
end
