# This file was generated by GoReleaser. DO NOT EDIT.
cask "kclipper" do
  desc "Kclipper Command Line Interface"
  homepage "https://github.com/macropower/kclipper"
  version "0.16.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kclipper"

  on_macos do
    on_intel do
      url "https://github.com/macropower/kclipper/releases/download/v0.16.0/kclipper_Darwin_x86_64.tar.gz"
      sha256 "2e27af2070cb5d23ced659bc2c414c2e1a2b441148acdda46be51aed61b91deb"
    end
    on_arm do
      url "https://github.com/macropower/kclipper/releases/download/v0.16.0/kclipper_Darwin_arm64.tar.gz"
      sha256 "c73bea1ee579a132a2fb82813a65c5ea60fd1e480f35786fb6a103c491f21675"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/macropower/kclipper/releases/download/v0.16.0/kclipper_Linux_x86_64.tar.gz"
      sha256 "8f500dedc226841eba8e8289bc2606efd02051cd018a0d53a49313cba5406800"
    end
    on_arm do
      url "https://github.com/macropower/kclipper/releases/download/v0.16.0/kclipper_Linux_arm64.tar.gz"
      sha256 "476e3f43616a57ad79dcce4d5d50d6653ce0016f9ab0bac861724a372219edf3"
    end
  end

  # No zap stanza required
end
